apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: localdb
  namespace: postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: localdb
      owner: localuser
      secret:
        name: localdb-secret
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
  postgresql:
    pg_hba:
    - host all all all md5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  5432: postgres/localdb-rw:5432
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: localdb-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": localdb
  podMetricsEndpoints:
  - port: metrics